# Runners details:
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

name: Manual test for package building

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "windows-2022", "windows-2019", "macos-13", "macos-12", "macos-11"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    name: Building job
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master

      - name: Initialize Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install build dependencies
        run: |
          pip install build

      - name: Build package
        run: python -m build && ls dist
